services:
  ok-api:
    image: ok-api
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    stdin_open: true
    tty: true
    develop:
      watch:
        - action: rebuild
          path: .